name: Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive
          fetch-depth: 0
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/alliedmodders/metamod-source
          git fetch upstream
      - name: Merge changes
        run: |
          git merge upstream/master
          git submodule update --init --recursive
      - name: Push changes
        run: |
          git push origin master